# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is a very simple function for portabl core detection.
#' @return The number of cores detected by your system
#' @export
number_of_cores <- function() {
    .Call(`_rTREES_number_of_cores`)
}

#' This function prepares the input files and runs simulator. Only the first three parameters are mandatory.
#' @param env_driver data.frame() containing environmental data for each time step. See Driver_inputs() for explanations of required columns. Use ValidateDriver() to check for errors.
#' @param base_parameters data.frame() where the first column is parameter names and the second column contains values. See Possible_parameters() for explanations of required parameters.
#' @param root_shoot_soil list() where each item is a vector for each type of parameter in orig param_mod file
#' @param which_out vector() of length 3 of boolean values to restrict which outputs are returned. Format is in order sim,hyd,leaf
#' @param softerror_max integer for how sensitive TREES should be before failing. This mostly exists to allow infrequent hydraulic errors to only stop the simulation if they occur a certain number of times.
#' @param verbosity true displays extra verbosity.
#'
#' @return a list of leaf areas, simulation outputs, and hydraulic outputs
#'
#' @examples
#' demo_standard_run<<-rTREES(
#'      env_driver = BuildDriver(ndays = 10),
#'      base_parameters = ExampleParameters(),
#'      root_shoot_soil = ExampleRSS()
#'  )
#' demo_cleaned_run<<-Clean_rTREES_output(
#'     rTREES_output = demo_standard_run
#'     )
#' @export
rTREES <- function(env_driver, base_parameters, root_shoot_soil, which_out = as.logical( c(1,1,1)), verbosity = FALSE, softerror_max = 5L) {
    .Call(`_rTREES_rTREES`, env_driver, base_parameters, root_shoot_soil, which_out, verbosity, softerror_max)
}

